--
-- PostgreSQL database dump
--

-- Dumped from database version 12.8 (Debian 12.8-1.pgdg100+1)
-- Dumped by pg_dump version 12.8 (Debian 12.8-1.pgdg100+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: medecin; Type: TABLE; Schema: public; Owner: superadmin
--

CREATE TABLE public.medecin (
    id integer NOT NULL,
    firstname text,
    lastname text
);


ALTER TABLE public.medecin OWNER TO superadmin;

--
-- Name: medecin_id_seq; Type: SEQUENCE; Schema: public; Owner: superadmin
--

ALTER TABLE public.medecin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medecin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patient; Type: TABLE; Schema: public; Owner: superadmin
--

CREATE TABLE public.patient (
    id integer NOT NULL,
    firstname text,
    lastname text
);


ALTER TABLE public.patient OWNER TO superadmin;

--
-- Name: patient_id_seq; Type: SEQUENCE; Schema: public; Owner: superadmin
--

ALTER TABLE public.patient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservation; Type: TABLE; Schema: public; Owner: superadmin
--

CREATE TABLE public.reservation (
    id integer NOT NULL,
    rdv timestamp with time zone,
    medecin_id integer,
    patient_id integer
);


ALTER TABLE public.reservation OWNER TO superadmin;

--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: superadmin
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: medecin; Type: TABLE DATA; Schema: public; Owner: superadmin
--

COPY public.medecin (id, firstname, lastname) FROM stdin;
1	Kent	Nelson
2	Eric	Strauss
3	Linda	Strauss
\.


--
-- Data for Name: patient; Type: TABLE DATA; Schema: public; Owner: superadmin
--

COPY public.patient (id, firstname, lastname) FROM stdin;
1	Joffrey	Semblant
2	Souffre	Douleur
3	UnSupo	Heoli
\.


--
-- Data for Name: reservation; Type: TABLE DATA; Schema: public; Owner: superadmin
--

COPY public.reservation (id, rdv, medecin_id, patient_id) FROM stdin;
1	2023-03-06 10:11:06+01	1	2
\.


--
-- Name: medecin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: superadmin
--

SELECT pg_catalog.setval('public.medecin_id_seq', 3, true);


--
-- Name: patient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: superadmin
--

SELECT pg_catalog.setval('public.patient_id_seq', 3, true);


--
-- Name: reservation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: superadmin
--

SELECT pg_catalog.setval('public.reservation_id_seq', 1, true);


--
-- Name: medecin medecin_pk; Type: CONSTRAINT; Schema: public; Owner: superadmin
--

ALTER TABLE ONLY public.medecin
    ADD CONSTRAINT medecin_pk PRIMARY KEY (id);


--
-- Name: patient patient_pk; Type: CONSTRAINT; Schema: public; Owner: superadmin
--

ALTER TABLE ONLY public.patient
    ADD CONSTRAINT patient_pk PRIMARY KEY (id);


--
-- Name: reservation reservation_pk; Type: CONSTRAINT; Schema: public; Owner: superadmin
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pk PRIMARY KEY (id);


--
-- Name: reservation reservation_medecin_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: superadmin
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_medecin_id_fk FOREIGN KEY (medecin_id) REFERENCES public.medecin(id);


--
-- Name: reservation reservation_patient_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: superadmin
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_patient_id_fk FOREIGN KEY (patient_id) REFERENCES public.patient(id);


--
-- PostgreSQL database dump complete
--

